### ISSUE TITLE
Add building instructions

### ISSUE THREAD

**Issue by pgundlach** [didierverna/etap#2]
etap looks totally awesome!

I'd like to build this on my macOS laptop. Could you provide building instruction?

**Comment by didierverna** [comment]
Yes, I will do so ASAP. Thanks for your interest!

**Comment by didierverna** [comment]
Hello,

I've updated the README file with some installation instructions. I'm doing it half-blind here so please try it out and tell me if the instructions are correct. BTW, if you're attending TUG 2023 physically, we can have a look at that during one of the coffee breaks ;-)

**Comment by pgundlach** [comment]
These instructions work very well! I can run etap, but still need to install the LM fonts. I will ask during coffee break which format (ttf, otf, ...?) to use.

**Comment by pgundlach** [comment]
I have got it to work by copying `lmroman10-regular.otf` to `$HOME/Library/Fonts/`.

Thank you very much! Excellent tool
