### ISSUE TITLE
Add screenshot in Readme

### ISSUE THREAD

**Issue by pgundlach** [didierverna/etap#3]
Sorry to bother again, but I think it might be worth to include a screenshot of the software in the Readme, so it might be easy to see what this is doing.

For example this one 

<img width="1194" alt="etap" src="https://github.com/didierverna/etap/assets/209434/b298bf26-439c-4889-99a9-028866d0fb22">

So you can use something like this in the Readme:

    <img width="1194" alt="etap" src="https://github.com/didierverna/etap/assets/209434/b298bf26-439c-4889-99a9-028866d0fb22">

**Comment by didierverna** [comment]
Good idea. It's done (in a slightly different way).
Thanks for the suggestion!
